### ISSUE TITLE
How do you accept new terms of service?

### ISSUE THREAD

**Issue by deefactorial** [bitfinexcom/bitfinex-terminal#13]
```sh
$node examples/backtest.js
/.../bitfinex-terminal/node_modules/dazaar/market.js:303
          self.emit('error', new Error('Terms of Use updated, new terms must be accepted before data can be replicated'))
                             ^

Error: Terms of Use updated, new terms must be accepted before data can be replicated
```

**Comment by robertkowalski** [comment]
@deefactorial thanks for submitting the issue. the terms of service are provided by a module called `bitfinex-terminal-terms-of-use`.

you can run `npm outdated` to see the latest version each module in an npm project. the current version is `4.0.0`.

then you update your package.json to the corresponding value,`4.0.0`:

```
    "bitfinex-terminal-terms-of-use": "^4.0.0",
```

afterwards, you need to run `npm install` to install the updated dependency

**Comment by deefactorial** [comment]
Ok, thank you, updating to the latest solved my issues.
