### ISSUE TITLE
👀 👀 👀 👀 👀 👀 👀

### ISSUE THREAD

**Issue by brentkirkland** [bitfinexcom/bitfinex-terminal#2]
🔥 🔥 🔥 🔥 🔥 🔥 🔥 

Looks exciting Paolo!

Keep up the good work and hello to everyone at BFX!

(sorry not an issue, this repo just caught my eyes 😄 )

**Comment by prdn** [comment]
hahahaha thanks man!

**Comment by Sadeghi1017** [comment]
> 🔥 🔥 🔥 🔥 🔥 🔥 🔥 
> 
> 
> 
> Looks exciting Paolo!
> 
> 
> 
> Keep up the good work and hello to everyone at BFX!
> 
> 
> 
> (sorry not an issue, this repo just caught my eyes 😄 )
